---
layout: post
title: "Python 강좌 : 제 30강 - 오류 발생"
tagline: "Python raise"
image: /assets/images/python.jpg
header:
  image: /assets/patterns/asanoha-400px.png
tags: ['Python']
keywords: Python, Python raise
ref: Python
category: posts
permalink: /posts/Python-30/
comments: true
---

## 오류 발생(raise) ##
----------

`오류 발생(raise)`은 프로그램이 허용된 범위 안에서 작동하지 않을 때 강제로 오류를 발생시키는 역할을 합니다.

코드상에서 문제는 없지만 알고리즘상에서 문제가 발생하거나 허용하지 않는 경우 강제로 오류를 발생시킵니다.

<br>
<br>

## 강제 오류 발생 ##
----------

{% highlight Python %}

fruit = ["apple", "banana", "grape", "watermelon"]
print(fruit)

while(True):
    index = input("과일 색인 값 선택: ")

    try:
        index = int(index)

        if index == 1:
            raise NameError

        else:
            print(fruit[index])

    except NameError:
        print("바나나는 불가능합니다.")

    except IndexError:
        print("해당 색인은 호출할 수 없습니다.")
    
    except ValueError:
        print("소수점은 사용할 수 없습니다.")

    print('------------')

{% endhighlight %}

**결과**
:    
['apple', 'banana', 'grape', 'watermelon']<br>
과일 색인 값 선택: 0<br>
apple<br>
------------<br>
과일 색인 값 선택: 1<br>
바나나는 불가능합니다.<br>
------------<br>
과일 색인 값 선택: 5<br>
해당 색인은 호출할 수 없습니다.<br>
------------<br>
과일 색인 값 선택: 9.5<br>
소수점은 사용할 수 없습니다.<br>
------------<br>

<br>

`raise 오류`를 통해 강제로 오류를 발생시킬 수 있습니다.

`index`가 1일 때 정상적으로 출력되는 것이 맞지만 허용하지 않는다면 `raise`를 통해 강제로 오류를 발생시킵니다.

1을 입력했을 때 `NameError`가 발생하며, `except` 구문으로 넘어갑니다.

<br>
<br>

## 사용자 정의 오류 발생 ##
----------

{% highlight Python %}

class AdminError(Exception):
    pass

while(True):
    
    admin = input("관리자 계정 입력: ")
    
    try:
        if admin != "yundaehee":
            raise AdminError()
        else:
            print("관리자 계정입니다.")

    except AdminError:
        print("관리자 계정이 아닙니다.")

    print('------------')

{% endhighlight %}

**결과**
:    
관리자 계정 입력: admin<br>
관리자 계정이 아닙니다.<br>
------------<br>
관리자 계정 입력: yundaehee<br>
관리자 계정입니다.<br>
------------<br>
<br>

클래스가 `Exception`을 상속 받는다면 사용자 정의 오류를 발생시킬 수 있습니다.

입력된 값이 `yundaehee`가 아니라면, `raise` 구문으로 넘어가게 되고, `AdminError` 클래스로 오류가 발생합니다.

`except` 구문에서 사용자 정의 오류를 예외 처리할 수 있습니다.